RottenPotatoes/config/routes.rb
Rottenpotatoes::Application.routes.draw do

  match 'movies/:id/similar' => 'movies#similar', :as => :similar_movies

  resources :movies

  root :to => 'movies#index'

end

RottenPotatoes/app/models/movie.rb
class Movie < ActiveRecord::Base
  attr_accessible :title, :rating, :description, :release_date, :director

  # List of Ratings used to classify the movies.
  RATINGS = Hash[%w(G PG PG-13 NC-17 R).map {|e| [e, e]}]

  # Set of Movies according to the given parameters.
  def self.movies(filters, sort_field)
    self.where({:rating => filters.values}).order(sort_field)
  end

  def self.same_director(director)
    self.where({:director => director})
  end
end

RottenPotatoes/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

RottenPotatoes/app/controllers/movies_controller.rb
class MoviesController < ApplicationController

  def index

    # Sets a redirection flag if a parameter is recalled from the session.
    def setup(param, default, redirect)
      if params[param.to_sym]
        session[param.to_sym] = params[param.to_sym]
        [params[param.to_sym], redirect]
      elsif session[param.to_sym]
        [session[param.to_sym], true]
      else
        [default, redirect]
      end
    end

    filters, redirect = setup('ratings', Movie::RATINGS, false)
    sort_by, redirect = setup('sort_by', nil, redirect)

    if redirect
      flash.keep
      redirect_to ratings: filters, sort_by: sort_by
    end

    @ratings = Movie::RATINGS
    @filters = filters
    @movies  = Movie.movies filters, sort_by
  end

  def show
    @movie = Movie.find params[:id]
  end

  def new; end

  def create
    @movie = Movie.create! params[:movie]
    flash[:notice] = "#{@movie.title} was succesfully created!"

    redirect_to movies_path
  end

  def edit
    @movie = Movie.find params[:id]
  end

  def update
    @movie = Movie.find params[:id]
    @movie.update_attributes! params[:movie]
    flash[:notice] = "#{@movie.title} was updated!"

    redirect_to movies_path
  end

  def destroy
    @movie = Movie.find params[:id]
    flash[:notice] = "'#{title}' was deleted!"
    @movie.destroy

    redirect_to movies_path
  end

  def similar
    @movie = Movie.find(params[:id])

    if @movie.director.to_s.empty?
      flash[:notice] = "'#{@movie.title}' has no director info."
      redirect_to movies_path
    end

    @movies = Movie.same_director(@movie.director)
  end
end

RottenPotatoes/app/helpers/application_helper.rb
module ApplicationHelper
end

RottenPotatoes/app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title Rotten Potatoes!
    = stylesheet_link_tag 'application'
    = javascript_include_tag 'application'
    = csrf_meta_tags

  %body
    %h1.title Rotten Potatoes!
    #main
      - if flash[:notice]
        #notice.message= flash[:notice]
      - elsif flash[:warning]
        #warning.message= flash[:warning]

      = yield

RottenPotatoes/app/views/movies/edit.html.haml
-# edit.html.haml using partial

%h1 Edit Existing Movie

= form_tag movie_path(@movie), :method => :put do

  = label :movie, :title, 'Title'
  = text_field :movie, 'title'

  = label :movie, :rating, 'Rating'
  = select :movie, :rating, Movie::RATINGS.keys

  = label :movie, :release_date, 'Released On'
  = date_select :movie, :release_date

  = label :movie, :director, 'Director'
  = text_field :movie, 'director'

  = submit_tag 'Update Movie Info'

RottenPotatoes/app/views/movies/index.html.haml
-#  This file is app/views/movies/index.html.haml
%h1 All Movies

= form_tag movies_path, {:id => :ratings_form, :method => :get} do
  Include:
  - @ratings.each_key do |rating|
    = rating
    = check_box_tag "ratings[#{rating}]", "#{rating}", (@filters.include? rating)
  = submit_tag 'Refresh', {:id => :ratings_submit}

%table#movies
  %thead
    %tr
      %th{:class => (:hilite if params[:sort_by] == 'title')}
        = link_to 'Movie Title', movies_path(:sort_by => :title), :id => :title_header
      %th Director
      %th Rating
      %th{:class => (:hilite if params[:sort_by] == 'release_date')}
        = link_to 'Release Date', movies_path(:sort_by => :release_date), :id => :release_date_header
      %th More Info

  %tbody
    - @movies.each do |movie|
      %tr
        %td= movie.title
        %td= movie.director
        %td= movie.rating
        %td= movie.release_date
        %td= link_to "More about #{movie.title}", movie_path(movie)

= link_to 'Add new movie', new_movie_path

RottenPotatoes/app/views/movies/new.html.haml
%h1 Create New Movie

= form_tag movies_path do

  = label :movie, :title, 'Title'
  = text_field :movie, 'title'

  = label :movie, :director, 'Director'
  = text_field :movie, 'director'

  = label :movie, :rating, 'Rating'
  = select :movie, :rating, Movie::RATIGNS.keys

  = label :movie, :release_date, 'Released On'
  = date_select :movie, :release_date

  = submit_tag 'Save Changes'

RottenPotatoes/app/views/movies/show.html.haml
-# in app/views/movies/show.html.haml

%h2 Details about #{@movie.title}

%ul#details
  %li
    Rating:
    = @movie.rating
  %li
    Released on:
    = @movie.release_date.strftime("%B %d, %Y")
  %li
    Director:
    = @movie.director

%h3 Description:

%p#description= @movie.description

= link_to 'Find Movies With Same Director', similar_movies_path(@movie)
= link_to 'Edit', edit_movie_path(@movie)
= button_to 'Delete', movie_path(@movie), :method => :delete, :confirm => 'Are you sure?'
= link_to 'Back to movie list', movies_path

RottenPotatoes/app/views/movies/similar.html.haml
-# in app/views/movies/simmilar.html.haml

%h2 Movies directed by #{@movies[0][:director]}

%ul
  - @movies.each do |movie|
    %li= movie.title

= link_to 'Back to movie list', movies_path